### ISSUE TITLE
Collapse block doesn't work

### ISSUE THREAD

**Issue by DubininDmitry** [vipzhicheng/logseq-plugin-vim-shortcuts#10]
Logseq 0.6.5 Linux Appimage
logseq-plugin-vim-shortcuts 0.15
When I try to collapse block using `zm` nothing happens.
But `zo` (Extend block) works good

**Comment by nashamri** [comment]
I have the same issue too.
Logseq 0.6.5 on linux
logseq-plugin-vim-shortcuts 0.15

**Comment by vipzhicheng** [comment]
I can reproduce this issue, seems related to Logseq API, I will let Logseq team know about this, but not sure when to solved, I think once it's fixed by Logseq Team, the function will be back automatically.

**Comment by DubininDmitry** [comment]
> I can reproduce this issue, seems related to Logseq API, I will let Logseq team know about this, but not sure when to solved, I think once it's fixed by Logseq Team, the function will be back automatically.

Thanks I got it. I closed this issue and I'll be waiting for a fix from Logseq team.

**Thanks a lot for a great plugin. I missed him a lot!**

**Comment by vipzhicheng** [comment]
Logseq has fixed it after v0.6.7, please upgrade Logseq.

**Comment by dmytrodubinin** [comment]
It works, thanks!
