### ISSUE TITLE
collapseAll and extendAll are disabled

### ISSUE THREAD

**Issue by usoonees** [vipzhicheng/logseq-plugin-vim-shortcuts#12]
https://github.com/vipzhicheng/logseq-plugin-vim-shortcuts/blob/014fc60495f7479756abe376031d8e61254b2f7f/src/main.ts#L119-L120

**Comment by vipzhicheng** [comment]
Logseq has a related bug before v0.6.7 so I disabled it. But after v0.6.7 the bug is fixed, I will release this feature asap.

**Comment by vipzhicheng** [comment]
It's released.
