### ISSUE TITLE
The mappings for `zm` and `zM` should be `zc` and `zC`

### ISSUE THREAD

**Issue by huyz** [vipzhicheng/logseq-plugin-vim-shortcuts#21]
If you look at the meanings of the vim mappings for folds https://riptutorial.com/vim/example/13101/opening--closing-and-toggling-folds you'll see that

`zc` is meant for closing the fold _under the cursor_.  `zm` doesn't care about the cursor.

Also, `o` is for "open" just as `c` is for "close". So they're much easier to remember as they're completely symmetric.

**Comment by vipzhicheng** [comment]
Thx for telling me that. I will change like this in next release.

**Comment by vipzhicheng** [comment]
Please upgrade to v0.1.11.

**Comment by huyz** [comment]
Thanks
