### ISSUE TITLE
`/` not working after update

### ISSUE THREAD

**Issue by 23727** [vipzhicheng/logseq-plugin-vim-shortcuts#23]
Hello, thanks for the plug-in

I've encountered behavior that I don't believe is intended—after updating the plug-in, when using `/` to search for a keyword, the cursor is not moved to the search box, so the mouse must be used to get it there. Also, once a search term is entered, no highlight is presented—I don't think it is working. 

Thank you, @vipzhicheng

**Comment by vipzhicheng** [comment]
Sorry for the issue, the update depends on a declaration to the market which was merged https://github.com/logseq/marketplace/pull/229, but I am not sure when it can take effect. So please try this feature later, I guess it may take effect after a new plugin was added to the market.
