### ISSUE TITLE
Outdated instructions for collapse shortcuts

### ISSUE THREAD

**Issue by TodorovicSrdjan** [vipzhicheng/logseq-plugin-vim-shortcuts#24]
First of all thanks for the plugin, I really like it.

I had problem with the collapse shortcuts. Letter `m` would always trigger `mark` command.  By inspecting repo for something else I stumble upon #21 and that was the reason for this problem.

I guess the change was made but docs/strings are not updated yet so I wanted to point it out just in case you are not aware of that.

**Comment by vipzhicheng** [comment]
Thanks, the readme looks outdated. Just updated.
