### ISSUE TITLE
How to activate?

### ISSUE THREAD

**Issue by fullofcaffeine** [vipzhicheng/logseq-plugin-vim-shortcuts#25]
Hi! 

Installed this, but it doesn't seem to work. Do I need to activate it somehow? I installed by cloning the repo and installing from it as an unpacked plugin. 

Thanks!

**Comment by vipzhicheng** [comment]
Why not by marketplace?

It need compile, you have 3 options.
1. source code, you need to know modern Javascript development.
2. download released assets. those are compiled version, but you need to know how to load unpacked plugin from Logseq.
3. install from marketplace, it's the easiest way.
