### ISSUE TITLE
[Feature change suggestion] Replace `hl` and `HL` mappings with each other

### ISSUE THREAD

**Issue by nocibambi** [vipzhicheng/logseq-plugin-vim-shortcuts#29]
I suggest replacing `hl` and `HL` with each other, that is, using `h` and `l` for block zoom/highlight navigation and `H` and `I` for block outdent/indent.

Reasoning:
- Mixing navigation (`jk`) and editing (`hl`) commands is confusing.
- `hjkl` commands suggest navigation in vim by default, not editing.
- Accidental `hl` commands can edit the text in unintended ways. When working with a big text body, this can quickly produce complicated editing errors.

**Comment by vipzhicheng** [comment]
You can change key bindings in the settings file to disable `hl` key bindings. The best action for `hl` would be cursor moving, but Logseq does not cursor in the non-editing mode for now. So I will change the `hl` behavior when cursor moving is supported.

**Comment by vipzhicheng** [comment]
done

**Comment by vipzhicheng** [comment]
Actually, I don't think it's a good idea, because `JK` are also highlight-line movements. `HL` are similar.

The best action for `hl` is cursor movement, which is not supported now.

Once Logseq supports cursor movement, I will assign `hl` to cursor movement.
