### ISSUE TITLE
[Feature Request] Shortcut to open links/pages/tags in a block

### ISSUE THREAD

**Issue by ivanddm** [vipzhicheng/logseq-plugin-vim-shortcuts#3]
Thanks a lot for this. I was really waiting for this plugin in Logseq, and it is working quite well 👍🏻

I was using Roam Research before with [roam-toolkit](https://github.com/roam-unofficial/roam-toolkit) plugin, and the only feature I miss from that one is to be able to open links/pages/tags with a shortcut.

Basically, that plugin adds a "hint" under each link when a block is highlighted so it can be accessed using just the keyboard. Something like this:

<img width="247" alt="CleanShot 2022-01-05 at 21 09 40@2x" src="https://user-images.githubusercontent.com/20104703/148267694-eb9ca2a2-e425-4fba-b0be-63bce6351454.png">

Perhaps there are other ways to do it, but that's just an idea.

Thanks in advance!

**Comment by vipzhicheng** [comment]
I just implemented this action in v0.0.2 using VIM-like combo action, Number+[ctrl+enter] to choose which one to go into.

For now the external link is not supported though.

**Comment by ivanddm** [comment]
Yes, it is working for me (num + cmd+shift+enter). Thanks a lot!
