### ISSUE TITLE
[Feature Request] Please enhancing the functionality of `d`

### ISSUE THREAD

**Issue by Immortal-Sty** [vipzhicheng/logseq-plugin-vim-shortcuts#39]
In Vim, we can use `d4k` and `d2j` to delete some blocks in front and behind. But it does not allow in Logseq.

**Comment by vipzhicheng** [comment]
In Logseq, all depends on Keybind API, it's hard to be that magical. If I implement a similar one, it would be `4dk` and `2dj`, but it's not Vim-like, do you think I should use this alternative solution?

**Comment by Immortal-Sty** [comment]
I feel it is feasible and better than nothing.

**Comment by vipzhicheng** [comment]
Done, please have a look. Actually, I added two new keybindings `dj` and `dk` and they support the preceding number.
