### ISSUE TITLE
[Feature Request] Customize shortcuts

### ISSUE THREAD

**Issue by Immortal-Sty** [vipzhicheng/logseq-plugin-vim-shortcuts#40]
Some shortcuts, such as "scroll to top", are different from Vim. But I want to change "go to graph view" to `gv` and "scroll to top" to `gg`.

**Comment by vipzhicheng** [comment]
Yes you can do that.

Step 1: Change logseq go graph view shortcut keybinding.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/1209538/234789882-c02a5eaa-fd85-44ed-8585-e8a94890adb5.png">

Step 2: Change vim shortcuts settings json file.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/1209538/234790106-9f994627-b1d2-46f5-882d-845aaf2ef249.png">

<img width="717" alt="image" src="https://user-images.githubusercontent.com/1209538/234790225-5bbe1d57-839c-4772-ba25-900f98e98df1.png">
