### ISSUE TITLE
Go to next/previous sibling commands do not work in zoomed edit mode

### ISSUE THREAD

**Issue by ches** [vipzhicheng/logseq-plugin-vim-shortcuts#41]
When one zooms into a block hierarchy with the built-in `Zoom in editing block` command (or clicking a block's bullet), the Vim Shortcuts plugin commands for moving to siblings do not seem to function.

## How to Reproduce

It's not convenient for me to make a recording at the moment, so I'll describe reproduction this way:

1. Create a hierarchy of blocks on a page like the following:

   ```
   - Parent
       - Child A
           - Grandchild A.1
       - Child B
           - Grandchild B.1
   ```
2. Zoom in to `Parent`, so it is the top level viewed.
3. Navigate to `Child A` in Normal mode
4. Try to move to `Child B` with `Shift-J`

This does not work for me, it works fine at the level of the page containing `Parent` but not in zoom.

## Thanks

Thanks very much for your Vim plugins! They are enhancing my experience with Logseq greatly, I'll be sending a coffee your way ☺️

**Comment by vipzhicheng** [comment]
I have done some fixes. but not perfect, Logseq API can not keep you stay on zoom mode, it will be redirected to the page and go to sibling blocks. I have contacted the Logseq dev team to see if they have some solutions. But for now, at least it works more or less.

**Comment by vipzhicheng** [comment]
My last comment issue has been fixed also.

**Comment by Weiming-Hu** [comment]
I'm curious whether this issue has been fixed. It seems like the moving to sibling functionality is still not working. Thank you very much for this plugin.
