### ISSUE TITLE
Next sibling stopped working.

### ISSUE THREAD

**Issue by tobealive** [vipzhicheng/logseq-plugin-vim-shortcuts#44]
Tested in logseq v0.9.8.

Prev sibling continues to work.

**Comment by vipzhicheng** [comment]
It should be a core API issue, please wait for my contact with Logseq Core Team.

**Comment by vipzhicheng** [comment]
Confirmed, it will be fixed in next release of Logseq by Core Team.

**Comment by vipzhicheng** [comment]
It's been fixed by Logseq Team in v0.9.9, please update.
