### ISSUE TITLE
[Feature] Add `A` for inserting at the end of the block

### ISSUE THREAD

**Issue by basepi** [vipzhicheng/logseq-plugin-vim-shortcuts#5]
My muscle memory is for `A` to insert at the end of the line in vim. Would this be easy to add? `A` should map the same as `i` currently does.

**Comment by redstreet** [comment]
+1 for this. Sorely needed.

Great plugin, thank you for writing this and sharing!

**Comment by redstreet** [comment]
Just noticed I can "Open settings" on the plugin and change the json to add the "A" shortcut. Thank  you!

Does this plugin support multiple shortcuts being assigned to the same function?

**Comment by basepi** [comment]
> Just noticed I can "Open settings" on the plugin and change the json to add the "A" shortcut.

Ooh this is excellent. Would be nice to support multiple shortcuts as well.

**Comment by vipzhicheng** [comment]
@basepi I want to know if you can change key binding in settings JSON file, does it need to support multiple shortcuts for one action?

**Comment by basepi** [comment]
@vipzhicheng It would be nice so we could have both `a` and `A` for example. (They do different things in vim, though due to the limitations of logseq they would do the same thing here)

For now I just don't have the capitalized versions bound, and it's fine, just not ideal for muscle memory.

**Comment by redstreet** [comment]
Agree with @basepi. It would be cool to have this support.

**Comment by vipzhicheng** [comment]
@basepi I have added `a` to do the same thing with `i` in v0.0.4, but can not add `A` at the same time because of Logseq limitation. Please give it a try.

**Comment by basepi** [comment]
@vipzhicheng works great with v0.0.4! Good to have `a` covered by default.

I still personally change `i` to `insertBefore` because that's what makes sense for my brain. But I think the defaults are OK, and love that it's easily customizable.

This is what I use, if anyone is curious:

```
  "insert": [
    "a"
  ],
  "insertBefore": [
      "i",
      "shift+i"
  ],
```
