### ISSUE TITLE
[Ctrl + Shift + Enter] Incorrectly follows Page names that are tagged

### ISSUE THREAD

**Issue by srparret** [vipzhicheng/logseq-plugin-vim-shortcuts#53]
**Problem**
If you to create a multiple word tag, it is a common practice to create a page and then tag that page, i.e  #[[multi word tag]].  As tags and pages are the same thing, This effectively gives the user the ability to have multi-worded tags.  When the first line is highlighted and the follow first link shortcut is pressed, the link that is followed only uses the first word of the tag, vs pulling the whole name of the page. 

**Example**
Following this tag
![image](https://github.com/vipzhicheng/logseq-plugin-vim-shortcuts/assets/12243844/01c2d472-4edd-454f-a3f2-70ca5e2271ce)

should take me too
![image](https://github.com/vipzhicheng/logseq-plugin-vim-shortcuts/assets/12243844/c240ff15-b882-4d20-8d53-ac138980bccd)

but instead takes me too
![image](https://github.com/vipzhicheng/logseq-plugin-vim-shortcuts/assets/12243844/2f1654f0-693a-44a2-a3f8-98b825cc222b)

I am using windows, and have not tested on multiple operating systems, but do not expect that to cause a significant difference.

**Comment by vipzhicheng** [comment]
fixed in v0.1.20, please have a try.
