### ISSUE TITLE
`dd` within a query result jumps to the original block

### ISSUE THREAD

**Issue by redstreet** [vipzhicheng/logseq-plugin-vim-shortcuts#54]
Thanks for the wonderful plugin!

Reporting a bug: if I use `dd` via the vim plugin to delete a block from within query results, it jumps to the original block's page, which is undesired. Thank you.

**Comment by vipzhicheng** [comment]
I tried to fix this issue, please update and have a try.

**Comment by redstreet** [comment]
Thank you! Just tried it. It doesn't jump to the original block any more. It does jump to an unexpected block though:

```
- 123
  - sub1
  - sub2
    - sub3
- delete this line using dd, and it will jump back to "123", while the expected jump is to "sub3"
```

However, this is still a great improvement over the original behavior, so thank you so much again!

**Comment by vipzhicheng** [comment]
em... That's what the best I can do. Because the focus behavior depends on jumping to a page.

**Comment by redstreet** [comment]
That's totally fine, it's very usable now. It's a huge improvement over jumping to an entirely different page, and I very much appreciate it, thank you!
