### ISSUE TITLE
How do I hide Visual/Normal indicator at the top right of the page?

### ISSUE THREAD

**Issue by senntore** [vipzhicheng/logseq-plugin-vim-shortcuts#55]
I can't seem to find a way for hiding this
![image](https://github.com/vipzhicheng/logseq-plugin-vim-shortcuts/assets/58325574/0afbc7d5-1234-4cfe-9680-00dbafc7583d)

It feels quite intrusive, maybe you could change Normal to just N & Visual to just V.
And since we are already notified of the change, I don't think it's necessary for it to be there all the time.
It would be great if you could add an option to hide this indicator.

**Comment by vipzhicheng** [comment]
It's there already.

![image](https://github.com/vipzhicheng/logseq-plugin-vim-shortcuts/assets/1209538/ae777d3c-9222-4c6d-9d43-be821c9b87b4)

**Comment by senntore** [comment]
@vipzhicheng That setting works just for the session when I uncheck it. After restarting Logseq, the indicator appears again even when it's not enabled in the settings.

**See the screenshot where I'm showing a journal page & the settings in another window:**
![Screenshot from 2024-01-19 19-25-18](https://github.com/vipzhicheng/logseq-plugin-vim-shortcuts/assets/58325574/ff553f1f-ada8-4399-8f20-65e952550b9f)

**Comment by vipzhicheng** [comment]
I released a patch, please have a test.

**Comment by senntore** [comment]
Thanks! It's working.
