### ISSUE TITLE
Visual Block Mode gets triggered when pasting something using ctrl+v

### ISSUE THREAD

**Issue by VoltaireNoir** [vipzhicheng/logseq-plugin-vim-shortcuts#6]
When editing a block, if you paste something from the clipboard using ctrl+v the Visual Block Mode is enabled. I don't think this is intended behavior, right? Also it would be great to be able to change the keybinding from ctrl+v to something else for the visual block mode. I couldn't find the setting for it.

**Comment by vipzhicheng** [comment]
Oh yes, that's because you are using Windows. I will try to solve this issue, you can change the settings by changing the settings JSON file which can be found at the plugin left bottom gear drop-down menu.

**Comment by vipzhicheng** [comment]
I just released a new version, and make ctrl+v can not be triggered in editing mode, please have a try.
